# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      DB_DATABASE: "book-app"
      DB_USER: root
      DB_PASS: root

    steps:   
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Start MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e "CREATE DATABASE IF NOT EXISTS \`$DB_DATABASE\`;" -u$DB_USER -p$DB_PASS
    - name: Run Sequelize Migrations
      run: |
        cd server
        npx sequelize-cli db:migrate
    - run: |
        cd server
        npm ci
    - run: |
        cd server
        npm run start --if-present
    - run: 
        cd server
        npm run test
    
    
